# Generated by Django 5.2.6 on 2025-09-25 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opportunities', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOpportunityNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunities.opportunity')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('preferences', models.CharField(default='', max_length=255)),
                ('alert_time', models.TimeField(default='07:00', help_text='Time of day to receive alerts (24-hour format)')),
                ('alert_days_ahead', models.PositiveIntegerField(default=7, help_text='How many days ahead to alert for deadlines')),
                ('alert_types', models.CharField(default='Job,Internship,Conference,Other', help_text='Comma-separated list of opportunity types to alert for', max_length=255)),
                ('notes', models.ManyToManyField(related_name='user_notes', through='users.UserOpportunityNotes', to='opportunities.opportunity')),
            ],
        ),
        migrations.AddField(
            model_name='useropportunitynotes',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='useropportunitynotes',
            unique_together={('user_profile', 'opportunity')},
        ),
    ]
