# Generated by Django 5.2.6 on 2025-09-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address for notifications', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='enable_notifications',
            field=models.BooleanField(default=True, help_text='Enable deadline notifications'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notification_method',
            field=models.CharField(choices=[('email', 'Email'), ('slack', 'Slack (Coming Soon)'), ('none', 'No Notifications')], default='email', help_text='How to receive notifications', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='slack_user_id',
            field=models.CharField(blank=True, help_text='Slack user ID for notifications (optional, coming soon)', max_length=50, null=True),
        ),
    ]
